	top u0 (
		.clk_clk                                                 (<connected-to-clk_clk>),                                                 //                                     clk.clk
		.ddr3_status_external_connection_export                  (<connected-to-ddr3_status_external_connection_export>),                  //         ddr3_status_external_connection.export
		.hip_ctrl_test_in                                        (<connected-to-hip_ctrl_test_in>),                                        //                                hip_ctrl.test_in
		.hip_ctrl_simu_mode_pipe                                 (<connected-to-hip_ctrl_simu_mode_pipe>),                                 //                                        .simu_mode_pipe
		.hip_pipe_sim_pipe_pclk_in                               (<connected-to-hip_pipe_sim_pipe_pclk_in>),                               //                                hip_pipe.sim_pipe_pclk_in
		.hip_pipe_sim_pipe_rate                                  (<connected-to-hip_pipe_sim_pipe_rate>),                                  //                                        .sim_pipe_rate
		.hip_pipe_sim_ltssmstate                                 (<connected-to-hip_pipe_sim_ltssmstate>),                                 //                                        .sim_ltssmstate
		.hip_pipe_eidleinfersel0                                 (<connected-to-hip_pipe_eidleinfersel0>),                                 //                                        .eidleinfersel0
		.hip_pipe_eidleinfersel1                                 (<connected-to-hip_pipe_eidleinfersel1>),                                 //                                        .eidleinfersel1
		.hip_pipe_eidleinfersel2                                 (<connected-to-hip_pipe_eidleinfersel2>),                                 //                                        .eidleinfersel2
		.hip_pipe_eidleinfersel3                                 (<connected-to-hip_pipe_eidleinfersel3>),                                 //                                        .eidleinfersel3
		.hip_pipe_powerdown0                                     (<connected-to-hip_pipe_powerdown0>),                                     //                                        .powerdown0
		.hip_pipe_powerdown1                                     (<connected-to-hip_pipe_powerdown1>),                                     //                                        .powerdown1
		.hip_pipe_powerdown2                                     (<connected-to-hip_pipe_powerdown2>),                                     //                                        .powerdown2
		.hip_pipe_powerdown3                                     (<connected-to-hip_pipe_powerdown3>),                                     //                                        .powerdown3
		.hip_pipe_rxpolarity0                                    (<connected-to-hip_pipe_rxpolarity0>),                                    //                                        .rxpolarity0
		.hip_pipe_rxpolarity1                                    (<connected-to-hip_pipe_rxpolarity1>),                                    //                                        .rxpolarity1
		.hip_pipe_rxpolarity2                                    (<connected-to-hip_pipe_rxpolarity2>),                                    //                                        .rxpolarity2
		.hip_pipe_rxpolarity3                                    (<connected-to-hip_pipe_rxpolarity3>),                                    //                                        .rxpolarity3
		.hip_pipe_txcompl0                                       (<connected-to-hip_pipe_txcompl0>),                                       //                                        .txcompl0
		.hip_pipe_txcompl1                                       (<connected-to-hip_pipe_txcompl1>),                                       //                                        .txcompl1
		.hip_pipe_txcompl2                                       (<connected-to-hip_pipe_txcompl2>),                                       //                                        .txcompl2
		.hip_pipe_txcompl3                                       (<connected-to-hip_pipe_txcompl3>),                                       //                                        .txcompl3
		.hip_pipe_txdata0                                        (<connected-to-hip_pipe_txdata0>),                                        //                                        .txdata0
		.hip_pipe_txdata1                                        (<connected-to-hip_pipe_txdata1>),                                        //                                        .txdata1
		.hip_pipe_txdata2                                        (<connected-to-hip_pipe_txdata2>),                                        //                                        .txdata2
		.hip_pipe_txdata3                                        (<connected-to-hip_pipe_txdata3>),                                        //                                        .txdata3
		.hip_pipe_txdatak0                                       (<connected-to-hip_pipe_txdatak0>),                                       //                                        .txdatak0
		.hip_pipe_txdatak1                                       (<connected-to-hip_pipe_txdatak1>),                                       //                                        .txdatak1
		.hip_pipe_txdatak2                                       (<connected-to-hip_pipe_txdatak2>),                                       //                                        .txdatak2
		.hip_pipe_txdatak3                                       (<connected-to-hip_pipe_txdatak3>),                                       //                                        .txdatak3
		.hip_pipe_txdetectrx0                                    (<connected-to-hip_pipe_txdetectrx0>),                                    //                                        .txdetectrx0
		.hip_pipe_txdetectrx1                                    (<connected-to-hip_pipe_txdetectrx1>),                                    //                                        .txdetectrx1
		.hip_pipe_txdetectrx2                                    (<connected-to-hip_pipe_txdetectrx2>),                                    //                                        .txdetectrx2
		.hip_pipe_txdetectrx3                                    (<connected-to-hip_pipe_txdetectrx3>),                                    //                                        .txdetectrx3
		.hip_pipe_txelecidle0                                    (<connected-to-hip_pipe_txelecidle0>),                                    //                                        .txelecidle0
		.hip_pipe_txelecidle1                                    (<connected-to-hip_pipe_txelecidle1>),                                    //                                        .txelecidle1
		.hip_pipe_txelecidle2                                    (<connected-to-hip_pipe_txelecidle2>),                                    //                                        .txelecidle2
		.hip_pipe_txelecidle3                                    (<connected-to-hip_pipe_txelecidle3>),                                    //                                        .txelecidle3
		.hip_pipe_txdeemph0                                      (<connected-to-hip_pipe_txdeemph0>),                                      //                                        .txdeemph0
		.hip_pipe_txdeemph1                                      (<connected-to-hip_pipe_txdeemph1>),                                      //                                        .txdeemph1
		.hip_pipe_txdeemph2                                      (<connected-to-hip_pipe_txdeemph2>),                                      //                                        .txdeemph2
		.hip_pipe_txdeemph3                                      (<connected-to-hip_pipe_txdeemph3>),                                      //                                        .txdeemph3
		.hip_pipe_txmargin0                                      (<connected-to-hip_pipe_txmargin0>),                                      //                                        .txmargin0
		.hip_pipe_txmargin1                                      (<connected-to-hip_pipe_txmargin1>),                                      //                                        .txmargin1
		.hip_pipe_txmargin2                                      (<connected-to-hip_pipe_txmargin2>),                                      //                                        .txmargin2
		.hip_pipe_txmargin3                                      (<connected-to-hip_pipe_txmargin3>),                                      //                                        .txmargin3
		.hip_pipe_txswing0                                       (<connected-to-hip_pipe_txswing0>),                                       //                                        .txswing0
		.hip_pipe_txswing1                                       (<connected-to-hip_pipe_txswing1>),                                       //                                        .txswing1
		.hip_pipe_txswing2                                       (<connected-to-hip_pipe_txswing2>),                                       //                                        .txswing2
		.hip_pipe_txswing3                                       (<connected-to-hip_pipe_txswing3>),                                       //                                        .txswing3
		.hip_pipe_phystatus0                                     (<connected-to-hip_pipe_phystatus0>),                                     //                                        .phystatus0
		.hip_pipe_phystatus1                                     (<connected-to-hip_pipe_phystatus1>),                                     //                                        .phystatus1
		.hip_pipe_phystatus2                                     (<connected-to-hip_pipe_phystatus2>),                                     //                                        .phystatus2
		.hip_pipe_phystatus3                                     (<connected-to-hip_pipe_phystatus3>),                                     //                                        .phystatus3
		.hip_pipe_rxdata0                                        (<connected-to-hip_pipe_rxdata0>),                                        //                                        .rxdata0
		.hip_pipe_rxdata1                                        (<connected-to-hip_pipe_rxdata1>),                                        //                                        .rxdata1
		.hip_pipe_rxdata2                                        (<connected-to-hip_pipe_rxdata2>),                                        //                                        .rxdata2
		.hip_pipe_rxdata3                                        (<connected-to-hip_pipe_rxdata3>),                                        //                                        .rxdata3
		.hip_pipe_rxdatak0                                       (<connected-to-hip_pipe_rxdatak0>),                                       //                                        .rxdatak0
		.hip_pipe_rxdatak1                                       (<connected-to-hip_pipe_rxdatak1>),                                       //                                        .rxdatak1
		.hip_pipe_rxdatak2                                       (<connected-to-hip_pipe_rxdatak2>),                                       //                                        .rxdatak2
		.hip_pipe_rxdatak3                                       (<connected-to-hip_pipe_rxdatak3>),                                       //                                        .rxdatak3
		.hip_pipe_rxelecidle0                                    (<connected-to-hip_pipe_rxelecidle0>),                                    //                                        .rxelecidle0
		.hip_pipe_rxelecidle1                                    (<connected-to-hip_pipe_rxelecidle1>),                                    //                                        .rxelecidle1
		.hip_pipe_rxelecidle2                                    (<connected-to-hip_pipe_rxelecidle2>),                                    //                                        .rxelecidle2
		.hip_pipe_rxelecidle3                                    (<connected-to-hip_pipe_rxelecidle3>),                                    //                                        .rxelecidle3
		.hip_pipe_rxstatus0                                      (<connected-to-hip_pipe_rxstatus0>),                                      //                                        .rxstatus0
		.hip_pipe_rxstatus1                                      (<connected-to-hip_pipe_rxstatus1>),                                      //                                        .rxstatus1
		.hip_pipe_rxstatus2                                      (<connected-to-hip_pipe_rxstatus2>),                                      //                                        .rxstatus2
		.hip_pipe_rxstatus3                                      (<connected-to-hip_pipe_rxstatus3>),                                      //                                        .rxstatus3
		.hip_pipe_rxvalid0                                       (<connected-to-hip_pipe_rxvalid0>),                                       //                                        .rxvalid0
		.hip_pipe_rxvalid1                                       (<connected-to-hip_pipe_rxvalid1>),                                       //                                        .rxvalid1
		.hip_pipe_rxvalid2                                       (<connected-to-hip_pipe_rxvalid2>),                                       //                                        .rxvalid2
		.hip_pipe_rxvalid3                                       (<connected-to-hip_pipe_rxvalid3>),                                       //                                        .rxvalid3
		.hip_serial_rx_in0                                       (<connected-to-hip_serial_rx_in0>),                                       //                              hip_serial.rx_in0
		.hip_serial_rx_in1                                       (<connected-to-hip_serial_rx_in1>),                                       //                                        .rx_in1
		.hip_serial_rx_in2                                       (<connected-to-hip_serial_rx_in2>),                                       //                                        .rx_in2
		.hip_serial_rx_in3                                       (<connected-to-hip_serial_rx_in3>),                                       //                                        .rx_in3
		.hip_serial_tx_out0                                      (<connected-to-hip_serial_tx_out0>),                                      //                                        .tx_out0
		.hip_serial_tx_out1                                      (<connected-to-hip_serial_tx_out1>),                                      //                                        .tx_out1
		.hip_serial_tx_out2                                      (<connected-to-hip_serial_tx_out2>),                                      //                                        .tx_out2
		.hip_serial_tx_out3                                      (<connected-to-hip_serial_tx_out3>),                                      //                                        .tx_out3
		.i2c_opencores_camera_export_scl_pad_io                  (<connected-to-i2c_opencores_camera_export_scl_pad_io>),                  //             i2c_opencores_camera_export.scl_pad_io
		.i2c_opencores_camera_export_sda_pad_io                  (<connected-to-i2c_opencores_camera_export_sda_pad_io>),                  //                                        .sda_pad_io
		.i2c_opencores_mipi_export_scl_pad_io                    (<connected-to-i2c_opencores_mipi_export_scl_pad_io>),                    //               i2c_opencores_mipi_export.scl_pad_io
		.i2c_opencores_mipi_export_sda_pad_io                    (<connected-to-i2c_opencores_mipi_export_sda_pad_io>),                    //                                        .sda_pad_io
		.mem_if_ddr3_emif_0_pll_ref_clk_clk                      (<connected-to-mem_if_ddr3_emif_0_pll_ref_clk_clk>),                      //          mem_if_ddr3_emif_0_pll_ref_clk.clk
		.mem_if_ddr3_emif_0_status_local_init_done               (<connected-to-mem_if_ddr3_emif_0_status_local_init_done>),               //               mem_if_ddr3_emif_0_status.local_init_done
		.mem_if_ddr3_emif_0_status_local_cal_success             (<connected-to-mem_if_ddr3_emif_0_status_local_cal_success>),             //                                        .local_cal_success
		.mem_if_ddr3_emif_0_status_local_cal_fail                (<connected-to-mem_if_ddr3_emif_0_status_local_cal_fail>),                //                                        .local_cal_fail
		.memory_mem_a                                            (<connected-to-memory_mem_a>),                                            //                                  memory.mem_a
		.memory_mem_ba                                           (<connected-to-memory_mem_ba>),                                           //                                        .mem_ba
		.memory_mem_ck                                           (<connected-to-memory_mem_ck>),                                           //                                        .mem_ck
		.memory_mem_ck_n                                         (<connected-to-memory_mem_ck_n>),                                         //                                        .mem_ck_n
		.memory_mem_cke                                          (<connected-to-memory_mem_cke>),                                          //                                        .mem_cke
		.memory_mem_cs_n                                         (<connected-to-memory_mem_cs_n>),                                         //                                        .mem_cs_n
		.memory_mem_dm                                           (<connected-to-memory_mem_dm>),                                           //                                        .mem_dm
		.memory_mem_ras_n                                        (<connected-to-memory_mem_ras_n>),                                        //                                        .mem_ras_n
		.memory_mem_cas_n                                        (<connected-to-memory_mem_cas_n>),                                        //                                        .mem_cas_n
		.memory_mem_we_n                                         (<connected-to-memory_mem_we_n>),                                         //                                        .mem_we_n
		.memory_mem_reset_n                                      (<connected-to-memory_mem_reset_n>),                                      //                                        .mem_reset_n
		.memory_mem_dq                                           (<connected-to-memory_mem_dq>),                                           //                                        .mem_dq
		.memory_mem_dqs                                          (<connected-to-memory_mem_dqs>),                                          //                                        .mem_dqs
		.memory_mem_dqs_n                                        (<connected-to-memory_mem_dqs_n>),                                        //                                        .mem_dqs_n
		.memory_mem_odt                                          (<connected-to-memory_mem_odt>),                                          //                                        .mem_odt
		.mipi_pwdn_n_external_connection_export                  (<connected-to-mipi_pwdn_n_external_connection_export>),                  //         mipi_pwdn_n_external_connection.export
		.mipi_reset_n_external_connection_export                 (<connected-to-mipi_reset_n_external_connection_export>),                 //        mipi_reset_n_external_connection.export
		.oct_rzqin                                               (<connected-to-oct_rzqin>),                                               //                                     oct.rzqin
		.pcie_256_hip_avmm_0_reconfig_clk_locked_fixedclk_locked (<connected-to-pcie_256_hip_avmm_0_reconfig_clk_locked_fixedclk_locked>), // pcie_256_hip_avmm_0_reconfig_clk_locked.fixedclk_locked
		.pcie_rstn_npor                                          (<connected-to-pcie_rstn_npor>),                                          //                               pcie_rstn.npor
		.pcie_rstn_pin_perst                                     (<connected-to-pcie_rstn_pin_perst>),                                     //                                        .pin_perst
		.pio_button_external_connection_export                   (<connected-to-pio_button_external_connection_export>),                   //          pio_button_external_connection.export
		.pio_led_external_connection_export                      (<connected-to-pio_led_external_connection_export>),                      //             pio_led_external_connection.export
		.pll_0_outclk1_100mhz_clk                                (<connected-to-pll_0_outclk1_100mhz_clk>),                                //                    pll_0_outclk1_100mhz.clk
		.pll_0_outclk2_20mhz_clk                                 (<connected-to-pll_0_outclk2_20mhz_clk>),                                 //                     pll_0_outclk2_20mhz.clk
		.refclk_clk                                              (<connected-to-refclk_clk>),                                              //                                  refclk.clk
		.reset_reset_n                                           (<connected-to-reset_reset_n>),                                           //                                   reset.reset_n
		.sdram_vfb_wire_addr                                     (<connected-to-sdram_vfb_wire_addr>),                                     //                          sdram_vfb_wire.addr
		.sdram_vfb_wire_ba                                       (<connected-to-sdram_vfb_wire_ba>),                                       //                                        .ba
		.sdram_vfb_wire_cas_n                                    (<connected-to-sdram_vfb_wire_cas_n>),                                    //                                        .cas_n
		.sdram_vfb_wire_cke                                      (<connected-to-sdram_vfb_wire_cke>),                                      //                                        .cke
		.sdram_vfb_wire_cs_n                                     (<connected-to-sdram_vfb_wire_cs_n>),                                     //                                        .cs_n
		.sdram_vfb_wire_dq                                       (<connected-to-sdram_vfb_wire_dq>),                                       //                                        .dq
		.sdram_vfb_wire_dqm                                      (<connected-to-sdram_vfb_wire_dqm>),                                      //                                        .dqm
		.sdram_vfb_wire_ras_n                                    (<connected-to-sdram_vfb_wire_ras_n>),                                    //                                        .ras_n
		.sdram_vfb_wire_we_n                                     (<connected-to-sdram_vfb_wire_we_n>),                                     //                                        .we_n
		.terasic_auto_focus_0_conduit_vcm_i2c_sda                (<connected-to-terasic_auto_focus_0_conduit_vcm_i2c_sda>),                //            terasic_auto_focus_0_conduit.vcm_i2c_sda
		.terasic_auto_focus_0_conduit_clk50                      (<connected-to-terasic_auto_focus_0_conduit_clk50>),                      //                                        .clk50
		.terasic_auto_focus_0_conduit_vcm_i2c_scl                (<connected-to-terasic_auto_focus_0_conduit_vcm_i2c_scl>),                //                                        .vcm_i2c_scl
		.terasic_camera_0_conduit_end_cam_d                      (<connected-to-terasic_camera_0_conduit_end_cam_d>),                      //            terasic_camera_0_conduit_end.cam_d
		.terasic_camera_0_conduit_end_cam_fval                   (<connected-to-terasic_camera_0_conduit_end_cam_fval>),                   //                                        .cam_fval
		.terasic_camera_0_conduit_end_cam_lval                   (<connected-to-terasic_camera_0_conduit_end_cam_lval>),                   //                                        .cam_lval
		.terasic_camera_0_conduit_end_cam_pix                    (<connected-to-terasic_camera_0_conduit_end_cam_pix>)                     //                                        .cam_pix
	);

